config/routes.rb
MyITCRM2::Application.routes.draw do

  resources :roles
  resources :permissions
  resources :permittables

  resources :users do
    collection do
      put :edit_profile
      put :update_profile
      put :register
    end
      resources :invoices, :work_orders
  end

  resources :pages
  resources :page_categories do
    get :page_category_name, :on => :collection
  end


  resources :statuses
  resources :priority_lists


  resources :work_orders do
    collection do
      put :close
      put :assign
    end
    resources :replies, :invoices, :tasks
  end
  resources :invoices do
     resources :product_invoice_lines, :service_invoice_lines
    end

  resources :settings do
    collection do
      get :index
      put :edit
    end
  end

  resources :product_categories do
    get :product_category_name, :on => :collection
  end

  resources :user_sessions

  resources :suppliers
  resources :products
  resources :service_rates
  resources :replies, :only => [:show, :edit, :update]
  resources :tasks, :only => [:index, :show, :edit, :update]
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/register' => 'users#register', :as => :register
  match '/clients' => 'users#clients', :as => :clients
  match '/employees' => 'users#employees', :as => :employees
  match 'profile/:id' => 'users#edit_profile', :as => :my_account
  match 'work_orders/:id/close' => 'work_orders#close', :as => :close
  match 'work_order/:id/assign' => 'work_orders#assign', :as => :assign
  match 'settings/edit' => 'settings#edit', :as => :edit

  match 'help/:page_id' => 'help#show'
  get '*page_category/:id' => 'pages#show', :only => [:show]



  root :to => 'user_sessions#new'











end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :service_invoice_lines, :dependent => :destroy
  has_many :product_invoice_lines, :dependent => :destroy
  belongs_to :user
  belongs_to :work_order

  attr_accessible :service_id, :product_id, :invoice_note, :user_id, :work_order_id,
                  :paid, :service_invoice_lines_attributes, :product_invoice_lines_attributes,
                  :created_by, :updated_by, :due_date, :qty, :service_id, :line_comment, :sku

  validates_uniqueness_of :work_order_id, :allow_blank => true
  validates_presence_of :due_date, :user_id

  accepts_nested_attributes_for :service_invoice_lines, :reject_if => lambda { |a| a[:qty].blank? || a[:service_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :product_invoice_lines, :reject_if => lambda { |a| a[:qty].blank? || a[:product_id].blank? }, :allow_destroy => true
  # Update Invoice Values
  before_save :update_invoice_values
  after_save :update_invoice_values
  after_initialize :update_invoice_values

  # Service lines totals
  def srv_price_totals
    service_invoice_lines.to_a.sum(&:total_price)
  end

  def srv_tax_totals
    service_invoice_lines.to_a.sum(&:tax)
  end

  def srv_sub_totals
    service_invoice_lines.to_a.sum(&:sub_total)
  end

# Product lines totals
  def prod_price_totals
    product_invoice_lines.to_a.sum(&:total_price)
  end

  def prod_tax_totals
    product_invoice_lines.to_a.sum(&:tax)
  end

  def prod_sub_totals
    product_invoice_lines.to_a.sum(&:sub_total)
  end

  def inv_price_totals
    service_invoice_lines.to_a.sum(&:total_price) + product_invoice_lines.to_a.sum(&:total_price)
  end

  def inv_tax_totals
    service_invoice_lines.to_a.sum(&:tax) + product_invoice_lines.to_a.sum(&:tax)
  end

  def inv_sub_totals
    service_invoice_lines.to_a.sum(&:sub_total) + product_invoice_lines.to_a.sum(&:sub_total)
  end

  # Used to update Invoice Totals on Save/Update
  def update_invoice_values
    self.sub_total = inv_sub_totals
    self.tax_total = inv_tax_totals
    self.total = inv_price_totals
  end


end

app/controllers/invoices_controller.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class InvoicesController < ApplicationController
  # mytodo - Add full language support.
  # mytodo - Add Mass Assignment restrictions.
  authorize_resource # Used by CanCan to restrict controller access

  def index
    @title = t 'global.invoices'
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.xml
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.xml
  def new
    @title = "Creating New Invoice"
    @invoice = Invoice.new
    if can? :create, Invoice
      service_invoice_line = @invoice.service_invoice_lines.build
      product_invoice_line = @invoice.product_invoice_lines.build

      if params[:user_id].blank? and current_user.employee
        redirect_to clients_url
        flash[:info] = "Please select a client first"
      end
    end
  end

  # GET /invoices/1/edit
  def edit
    @title = "Edit Invoice"
    @invoice = Invoice.find(params[:id])
    service_invoice_line = @invoice.service_invoice_lines.build
    product_invoice_line = @invoice.product_invoice_lines.build

  end

  # POST /invoices
  # POST /invoices.xml
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully created.') }
        format.xml { render :xml => @invoice, :status => :created, :location => @invoice }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.xml
  def update
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => 'edit' }
        format.xml { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.xml
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to(invoices_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/invoices_helper.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014 Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module InvoicesHelper

  def open_invoices
    @open_invoices = Invoice.where("paid = ?",false)
  end

  def paid_invoices
    @paid_invoices = Invoice.where("paid = ?",true)
  end

  def client_info
    if @invoice.work_order_id.present?
     user = WorkOrder.find(@invoice.work_order_id)
     user_id = user.user_id
    else
     user = User.find(@invoice.user_id)
      user_id = user.id
    end
     @client_info = User.find(user_id)
  end

  def service_invoice_lines
     @service_invoice_lines = ServiceInvoiceLine.where("invoice_id = ? ","#{params[:id]}")
  end

  def product_invoice_lines
    @product_invoice_lines = ProductInvoiceLine.where("invoice_id = ? ","#{params[:id]}")
  end

  def payment_status(paid)
    if paid.present?
      "<p>Payment Status = <a class='paid'>PAID</a></p>".html_safe
    end
    if paid.blank?
      "<p>Payment Status = <a class='unpaid'>UNPAID</a></p>".html_safe
    end
  end
  # This is used to display a invoice status stamp on the invoice
  def invoice_stamp(paid, due_date)
    # If this invoice is paid in full, then display the PAID stamp
    if paid
      text = t "invoice.paid"
      "<a class='paid'>#{text}</a>".html_safe
    else
        # If we have a due_date, lets use that to see if the invoice is OVERDUE, if not stamp it with UNPAID
        if due_date.present?
          if due_date + 86399 < Time.now
          text = t "invoice.overdue"
          "<a class='overdue'>#{text}</a>".html_safe
          else
           text = t "invoice.unpaid"
          "<a class='unpaid'>#{text}</a>".html_safe
        end
        end
    end
  end

   def wo_details
    @wo_details = WorkOrder.where("id = ?", @invoice.work_order_id).first
   end

  def active_service_rates
    ServiceRate.where('active = ?', true).order('description')
  end

  def active_parts_rates
    Product.where('active = ?', true).order('description')
  end
end

app/views/invoices/_form.html.erb
<div class="span10">
<%= simple_form_for @invoice, :html => {:class => "form-horizontal"} do |f| %>

      <%= f.input :paid %>
      <%= f.input :due_date, :as => :date_picker %>
      <div>
        <h3 align="center">Service Charges</h3>
        <table id="lines" class="table table-bordered table-condensed">
          <thead>
          <tr>
            <th>Qty</th>
            <th>Service Rate</th>
            <th>Line Comments</th>
            <th>Line Actions</th>
          </tr>
          </thead>

          <tbody>
          <%= f.fields_for :service_invoice_lines do |builder| %>
              <%= render "invoices/service_invoice_line", :f => builder %>
          <% end %>
          <%= link_to_add_fields 'Add Services', f, :service_invoice_lines, 'services' %>
          </tbody>
        </table>
      </div>


   <div>
     <h3 align="center">Part/Material Charges</h3>
     <table id="lines2" class="table table-bordered table-condensed">
       <thead>
       <tr>
         <th>Qty</th>
         <th>Parts/Materials Rate</th>
         <th>Line Comments</th>
         <th>Line Actions</th>
       </tr>
       </thead>

       <tbody>
       <%= f.simple_fields_for :product_invoice_lines do |builder| %>
           <%= render "invoices/product_invoice_line", :f => builder %>
       <% end %>
       <%= link_to_add_fields 'Add Products', f, :product_invoice_lines, 'products' %>
       </tbody>

     </table>
   </div>


      <%= f.input :invoice_note, :input_html => {:rows => 10, :cols => 100, :value => Setting::default_invoice_note }  %>

    <%= f.hidden_field :work_order_id, :value => params[:work_order_id] if params[:work_order_id].present? %>
    <%= f.hidden_field :user_id, :value => params[:user_id] if params[:user_id].present? %>
    <%= f.hidden_field :created_by, :value => current_user.username if @invoice.created_by.blank? %>
    <%= f.hidden_field :updated_by, :value => current_user.username %>

      <div class="form-actions">
                     <%= f.submit nil, :class => "btn btn-primary" %>
                     <%= link_to t("global.cancel"), invoices_path, :class => "btn" %>
                   </div>

<% end %>
</div>
<div class="span2">
  <ul>
    <% if can? :destroy, WorkOrder and @invoice.id.present?  %>
        <li class="print"><%= link_to (t "global.print"), invoice_path(@invoice.id) %></li>
        <li class="delete"><%= link_to (t "global.delete"), invoice_path, :confirm => 'Are you sure?', :method => :delete  %> </li>
    <% end %>
    <% if can? :edit, WorkOrder and @invoice.id.present?  %>
        <li class="edit"><%= link_to (t "global.edit"), edit_invoice_path %></li>
    <% end %>
    <li class="exit"><%= link_to (t "global.exit"), invoices_path %></li>
  </ul>
</div>


app/views/invoices/_open_tab.html.erb
<table class="table table-bordered table-hover table table-condensed">
  <thead>
      <tr>
          <th><%= t('invoice.invoice_id') %></th>
          <th><%= t('global.due_date') %></th>
          <th><%= t('invoice.wo_id') %></th>
          <th><%= t('invoice.clients_name') %></th>
          <th><%= t('invoice.sub_total') %></th>
          <th><%= t('invoice.tax_total') %></th>
          <th><%= t('invoice.total') %></th>
          <th><%= t('global.actions') %></th>
      </tr>
    </thead>
    <tbody>
    <% @open_invoices.each do |open| %>
        <tr <% if open.due_date < Date.today %> class="error" <% end %>>
            <td><%= link_to(open.id, invoice_path(open.id)) %></td>
            <td><% if open.due_date < Date.today %>
                  <span class="badge badge-important"><%= l open.due_date, :format => :short %></span>
                    <% else %>
                  <%= l open.due_date, :format => :short %>
              <%end %>
            </td>
            <td><%= link_to open.work_order_id, work_order_path(open.work_order_id) if open.work_order_id.present? %></td>
            <td><%= link_to(open.user.name, user_path(open.user_id)) if open.user_id.present? %></td>
            <td><%= number_to_currency(open.sub_total) %></td>
            <td><%= number_to_currency(open.tax_total) %></td>
            <td><%= number_to_currency(open.total) %></td>

            <td>
                <%= link_to(image_tag('view.png', :title => ( t('global.view'))), invoice_path(open.id) )%>&nbsp;
                <%= link_to(image_tag('edit.png', :title => (t('global.edit'))), edit_invoice_path(open.id)) %>&nbsp;
             <% if can? :manage, Invoice %>
                <%= link_to(image_tag('printer.png', :title => (t('global.print'))), invoice_path(open.id,:format => 'pdf'))%>&nbsp;
                <%= link_to(image_tag('delete.png', :title => (t('global.delete'))), invoice_path(open.id), :confirm => t('alert.destroy'), :method => :delete ) %>&nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/invoices/_paid_tab.html.erb
<table width="100%" cellspacing="0">



</table>

<table class="table table-bordered table-hover table table-condensed">
  <thead>
      <tr>
          <th><%= t "invoice.invoice_id" %></th>
          <th><%= t "invoice.wo_id" %></th>
          <th><%= t "invoice.clients_name" %></th>
          <th><%= t "invoice.sub_total" %></th>
          <th><%= t "invoice.tax_total" %></th>
          <th><%= t "invoice.total" %></th>
          <th><%= t "invoice.note" %></th>
          <th><%= t "global.actions" %></th>
      </tr>
    </thead>
    <tbody>
    <% @paid_invoices.each do |closed| %>
        <tr>
            <td align="center"><%= link_to(closed.id, invoice_path(closed.id)) %></td>
            <td align="center"><%= closed.work_order_id %></td>
            <!--myTODO : Username Not showing-->
            <td align="center"><%= link_to(closed.user.name, user_path(closed.user_id)) if closed.user_id.present? %></td>
            <td align="center"><%= number_to_currency(closed.sub_total) %></td>
            <td align="center"><%= number_to_currency(closed.tax_total) %></td>
            <td align="center"><%= number_to_currency(closed.total) %></td>
            <td><%= truncate(closed.invoice_note, :length => 75) %></td>

            <td width="120" align="center">
                <%= link_to(image_tag('view.png', :title => (t "global.view")), invoice_path(closed.id) )%>&nbsp;
                <%= link_to(image_tag('edit.png', :title => (t "global.edit")), edit_invoice_path(closed.id)) %>&nbsp;
             <% if can? :manage, WorkOrder %>
                <%= link_to(image_tag('printer.png', :title => (t "global.print")), invoice_path(closed.id,:format => 'pdf'))%>&nbsp;
                <%= link_to(image_tag('delete.png', :title => (t "global.delete")), invoice_path(closed.id), :confirm => (t "alert.destroy"), :method => :delete ) %>&nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/invoices/_product_invoice_line.erb
  <tr >
    <td><%= f.number_field :qty, :style => 'width:50px' %></td>
    <td><%= f.collection_select :product_id, active_parts_rates, :id, :product_lookup, :include_blank => true,  :style => 'width:90%;' %></td>
    <td><%= f.text_field :line_comment, :style => 'width:90%;' %></td>
    <td><%= link_to 'Remove', 'products',  class: 'remove_fields btn btn-small btn-danger' %></td>
  </tr>

app/views/invoices/_service_invoice_line.erb
<tr>
    <td><%= f.number_field :qty, :style => 'width:50px;' %></td>
    <td><%= f.collection_select :service_id, active_service_rates, :id, :rate_lookup, :include_blank => true, :class => 'span3' %></td>
    <td><%= f.text_field :line_comment, :style => 'width:90%;' %></td>
    <td><%= link_to 'Remove', 'services', class: 'remove_fields btn btn-small btn-danger' %></td>
</tr>






app/views/invoices/edit.html.erb
 <%= render 'form' %>

app/views/invoices/index.html.erb
<div class="row-fluid">
<div class="span10">
  <div class="tabbable"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#open" data-toggle="tab"><%= t "invoices.tab_menu_open" %>&nbsp;<% if open_invoices.count > 0 %><span class="badge badge-important"><%= open_invoices.count %></span><% end %></a></li>
      <li><a href="#paid" data-toggle="tab"><%= t "invoices.tab_menu_paid" %>&nbsp;<% if paid_invoices.count > 0 %><span class="badge badge-success"><%= paid_invoices.count %></span><% end %></a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="open">
        <p><%= render(:partial => 'invoices/open_tab') %></p>
      </div>
      <div class="tab-pane" id="paid">
        <p><%= render(:partial => 'invoices/paid_tab') %></p>
      </div>
    </div>
  </div>
  </div>

<div class="span2">
    <% if can? :create, Invoice %>
            <%= menu_button t("global.create"), new_invoice_path, "icon-pencil icon-white" %>
    <% end %>
  </div>
</div>

app/views/invoices/new.html.erb
<div class="span12">
    <%= render 'form' %>
</div>


app/views/invoices/show.html.erb
<div class="span10">
  <h1 align="center">INVOICE #<%= @invoice.id %></h1>
  <div style="text-align: right">
    <p></p>
    <p></p>
  </div>
    <div class="row-fluid">
      <div class="span3">
        <h4>Bill To:</h4>
        <p><%= t "invoice.billing_account" %><%= @invoice.user_id %></p>
        <address>
          <strong><%= client_info.name %></strong><br>
          <% if client_info.address? %>
              <%= client_info.address %><br>
              <%= client_info.city %>,<%= client_info.state %>, <%= client_info.zip %><br>
          <% end %>
          <% if client_info.phone?%><abbr title="Phone">P: </abbr><%= client_info.phone %><br><% end %>
          <% if client_info.mobile?%><abbr title="Mobile">M: </abbr><%= client_info.mobile %><br><% end %>
          <% if client_info.fax?%><abbr title="Fax">F: </abbr><%= client_info.fax %><br><% end %>
          <% if client_info.email?%><abbr title="Email">E: </abbr><a href="mailto:'<%= client_info.email  %>'"><%= client_info.email  %></a><% end %>
        </address>
      </div>
      <div class="span3 offset6" >
        <h4>Bill From:</h4>
        <address>
          <strong><%= Setting::business_name %></strong><br>
          <%= Setting::business_address %><br>
          <% if Setting::business_phone?%><abbr title="Phone">P: </abbr><%= Setting::business_phone %><br><% end %>
          <% if Setting::business_toll_free?%><abbr title="Toll Free">TF: </abbr><%= Setting::business_toll_free %><br><% end %>
          <% if Setting::business_fax %><abbr title="Fax">F: </abbr><%= Setting::business_fax %><br><% end %>
          <% if Setting::business_email %><abbr title="Email">E: </abbr><a href="mailto:'<%= Setting::business_email  %>'"><%= Setting::business_email  %></a><% end %>
        </address>
      </div>
    </div>
  <div class="span7">
    <% if @invoice.work_order_id %>
        <table class="table table-condensed table-bordered">
          <caption><strong>Work Order Details</strong> </caption>
          <thead>
          <tr>
            <th><%= t "workorder.pdf.t_workorder" %></th>
            <th>Description</th>
            <th>Completed</th>
          </tr>
          </thead>
          <tbody>
          <tr class="success">
            <td>#<%= @invoice.work_order_id %></td>
            <td><%=truncate wo_details.subject, :length => 20 %></td>
            <td><%= l wo_details.closed_date, :format => :default %> <%= t "global.by" %> <%= wo_details.assigned_to_username  %></td>
          </tr>
          </tbody>
        </table>
    <% end %>
  </div>
  <div class="span2 offset2">
    <table class="table table-condensed table-bordered">
      <caption><strong>Invoice Dates</strong></caption>
      <thead>
      <tr>
        <th>Created:</th>
        <th>Due:</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= l @invoice.created_at, :format => :short  %></td>
        <td> <%= l @invoice.due_date, :format => :default if @invoice.due_date.present?  %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <div>
    <% if service_invoice_lines.present? %>
        <table class="table table-condensed table-bordered table-striped">
          <caption>Service's</caption>
          <thead>
          <tr>
            <th>Qty</th>
            <th>SKU</th>
            <th>Description</th>
            <th>Price</th>
            <th>Sub Total</th>
            <th>Tax</th>
            <th>Total</th>
          </tr>
          </thead>
          <tbody>
          <% service_invoice_lines.each do |lines| %>
              <tr>
                <td><%= lines.qty %></td>
                <td><%= lines.sku %></td>
                <td><%= lines.description %>
                  <br/>
                  <em style="font-size: 0.8em"><%= lines.line_comment %></em>
                </td>
                <td><%= number_to_currency lines.price %></td>
                <td><%= number_to_currency lines.sub_total %></td>
                <td><%= number_to_currency lines.tax %> </td>
                <td><%= number_to_currency lines.total_price %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <div class="row-fluid">
          <div class="span12" style="font-size: 0.8em">
            <div class="span3 offset9" style="text-align: right">
              <table>
                <tbody>
                <tr>
                  <td>Service's Sub Total:</td>
                  <td><strong><%= number_to_currency @invoice.srv_sub_totals %></strong></td>
                </tr>
                <tr>
                  <td>Service's Tax  <%= Setting::tax_type %>:</td>
                  <td><strong><%= number_to_currency @invoice.srv_tax_totals %></strong></td>
                </tr>
                <tr>
                  <td>Service's Total:</td>
                  <td><strong><%= number_to_currency @invoice.srv_price_totals %></strong></td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

    <% end %>
  </div>
  <% if product_invoice_lines.present? %>
      <table class="table table-condensed table-bordered table-striped">
        <caption>Parts</caption>
        <thead>
        <tr>
          <th>Qty</th>
          <th>SKU</th>
          <th>Description</th>
          <th>Price</th>
          <th>Sub Total</th>
          <th>Tax</th>
          <th>Total</th>
        </tr>
        </thead>
        <tbody>
        <% product_invoice_lines.each do |lines| %>
            <tr>
              <td><%= lines.qty %></td>
              <td><%= lines.sku %></td>
              <td><%= lines.description %>
                <br/>
                <em style="font-size: 0.8em"><%= lines.line_comment %></em>
              </td>
              <td><%= number_to_currency lines.price %></td>
              <td><%= number_to_currency lines.sub_total %></td>
              <td><%= number_to_currency lines.tax %> </td>
              <td><%= number_to_currency lines.total_price %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="row-fluid">
        <div class="span12" style="font-size: 0.8em">
          <div class="span3 offset9" style="text-align: right">
            <table>
              <tbody>
              <tr>
                <td>Parts Sub Total:</td>
                <td><strong><%= number_to_currency @invoice.prod_sub_totals %></strong></td>
              </tr>
              <tr>
                <td>Parts Tax <%= Setting::tax_type %>:</td>
                <td><strong><%= number_to_currency @invoice.prod_tax_totals %></strong></td>
              </tr>
              <tr>
                <td>Parts Total:</td>
                <td><strong><%= number_to_currency @invoice.prod_price_totals %></strong></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  <% end %>
<!--Invoice Totals here-->
<hr/>
  <div class="row-fluid">
    <div class="span12" style="font-size: 1em">
      <div class="span4">
        <% if @invoice.invoice_note.present? then %>

              <h5>Invoice note:</h5>
              <p><%= @invoice.invoice_note %></p>

        <% end %>
      </div>
      <div class="span3 offset5" style="text-align: right">
        <table>
          <tbody>
          <tr>
            <td>Invoice Sub Total:</td>
            <td><strong><%= number_to_currency @invoice.inv_sub_totals %></strong></td>
          </tr>
          <tr>
            <td>Invoice Tax <%= Setting::tax_type %>:</td>
            <td><strong><%= number_to_currency @invoice.inv_tax_totals %></strong></td>
          </tr>
          <tr>
            <td>Invoice Total:</td>
            <td><strong><%= number_to_currency @invoice.inv_price_totals %></strong></td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <hr/>
</div><!--end of span10-->


<div class="span2">
  <ul>
    <% if @invoice.paid.blank? %>
        <li class="edit"><%= link_to (t "global.edit"), edit_invoice_path if can? :edit, Invoice  %></li>
    <% end %>
    <li class="print"><%= link_to (t "global.print"), invoice_path(@invoice.id) if can? :read, Invoice %></li>
    <hr>
    <li class="delete"><%= link_to (t "global.delete"), invoice_path, :confirm => 'Are you sure?', :method => :delete  if can? :manage, Invoice %> </li>
    <hr>
    <li class="exit"><%= link_to (t "global.exit"), invoices_path if can? :read, Invoice %></li>
  </ul>
  <p>Created <%= l @invoice.created_at, :format => :short %> <%= t "global.by" %> <%= @invoice.created_by %></p>
  <p>Updated <%= time_ago_in_words @invoice.updated_at %> <%= t "global.ago" %> <%= t "global.by" %> <%= @invoice.updated_by if present? %><%= @invoice.created_by if @invoice.updated_by.blank? %></p>
  <%= payment_status @invoice.paid? %>
</div>

