config/routes.rb
MyITCRM2::Application.routes.draw do

  resources :roles
  resources :permissions
  resources :permittables

  resources :users do
    collection do
      put :edit_profile
      put :update_profile
      put :register
    end
      resources :invoices, :work_orders
  end

  resources :pages
  resources :page_categories do
    get :page_category_name, :on => :collection
  end


  resources :statuses
  resources :priority_lists


  resources :work_orders do
    collection do
      put :close
      put :assign
    end
    resources :replies, :invoices, :tasks
  end
  resources :invoices do
     resources :product_invoice_lines, :service_invoice_lines
    end

  resources :settings do
    collection do
      get :index
      put :edit
    end
  end

  resources :product_categories do
    get :product_category_name, :on => :collection
  end

  resources :user_sessions

  resources :suppliers
  resources :products
  resources :service_rates
  resources :replies, :only => [:show, :edit, :update]
  resources :tasks, :only => [:index, :show, :edit, :update]
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/register' => 'users#register', :as => :register
  match '/clients' => 'users#clients', :as => :clients
  match '/employees' => 'users#employees', :as => :employees
  match 'profile/:id' => 'users#edit_profile', :as => :my_account
  match 'work_orders/:id/close' => 'work_orders#close', :as => :close
  match 'work_order/:id/assign' => 'work_orders#assign', :as => :assign
  match 'settings/edit' => 'settings#edit', :as => :edit

  match 'help/:page_id' => 'help#show'
  get '*page_category/:id' => 'pages#show', :only => [:show]



  root :to => 'user_sessions#new'











end

app/models/service_rate.rb
class ServiceRate < ActiveRecord::Base
  has_many :service_invoice_lines

  attr_accessible :sku, :description, :rate, :taxable, :tax_rate, :active
  validates_presence_of :sku, :description, :rate, :tax_rate, :active
  validates_uniqueness_of :sku

  def rate_lookup
     "[#{sku}]-#{description} - #{I18n.t 'number.currency.format.unit'}#{rate}"
  end

end

app/controllers/service_rates_controller.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class ServiceRatesController < ApplicationController
  authorize_resource
  # GET /service_rates
  # GET /service_rates.xml
  def index
    @title = 'Service Rates'
    @service_rates = ServiceRate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @service_rates }
    end
  end

  # GET /service_rates/1
  # GET /service_rates/1.xml
  def show
    @title = 'Service Rate Details'
    @service_rate = ServiceRate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @service_rate }
    end
  end

  # GET /service_rates/new
  # GET /service_rates/new.xml
  def new
    @title = 'Creating New Service Rate'
    @service_rate = ServiceRate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @service_rate }
    end
  end

  # GET /service_rates/1/edit
  def edit
    @title = 'Editing Service Rate'
    @service_rate = ServiceRate.find(params[:id])
  end

  # POST /service_rates
  # POST /service_rates.xml
  def create
    @title = 'Adding New Service Rate'
    @service_rate = ServiceRate.new(params[:service_rate])

    respond_to do |format|
      if @service_rate.save
        format.html { redirect_to service_rates_path, :notice => 'Service rate was successfully created.' }
        format.xml { render :xml => @service_rate, :status => :created, :location => @service_rate }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @service_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /service_rates/1
  # PUT /service_rates/1.xml
  def update
    @service_rate = ServiceRate.find(params[:id])

    respond_to do |format|
      if @service_rate.update_attributes(params[:service_rate])
        format.html { redirect_to service_rates_path, :notice => 'Service rate was successfully updated.' }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @service_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /service_rates/1
  # DELETE /service_rates/1.xml
  def destroy
    @service_rate = ServiceRate.find(params[:id])
    @service_rate.destroy

    respond_to do |format|
      format.html { redirect_to(service_rates_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/service_rates_helper.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module ServiceRatesHelper
end

app/views/service_rates/_form.html.erb
    <%= simple_form_for @service_rate, :html => { :class => "form-horizontal"} do |f| %>
      <%= f.error_notification %>

        <%= f.input :sku %>

        <%= f.input :description %>

        <%= f.input :rate %>

        <%= f.input :taxable %>

        <% if @service_rate.tax_rate.present? %>
            <%= f.input :tax_rate %>
        <% else %>
           <%= f.input :tax_rate, :hint => t("products.hint_tax_rate") , :input_html => {:value => Setting::tax_rate} %>
        <% end %>

        <%= f.input :active %>


        <div class="form-actions span10">
          <%= f.submit nil, :class => "btn btn-primary" %>
          <%= link_to t("global.cancel"), :back, :class => "btn" %>
        </div>

    <% end %>

app/views/service_rates/edit.html.erb
<div id="sidebar_left">
  <%= module_header %>
  <div class="module">
    <ul>
        <li class="exit"><%= link_to (t "global.exit"), service_rates_path %></li>
    </ul>
  </div>
  <%= render 'layouts/left_sidebar_modules' %>
</div>
<div id="center_col">

  <%= render 'form' %>

</div>


app/views/service_rates/index.html.erb
<div class="row-fluid">
  <div class="span10">
    <table class="table table-bordered table-hover table table-condensed">

      <thead>
      <tr>
        <th>SKU</th>
        <th>Description</th>
        <th>Rate</th>
        <th>Taxable</th>
        <th>Tax rate</th>
        <th><%= t "global.active" %></th>
        <th><%= t "global.actions" %></th>
      </tr>
      </thead>
      <tbody>
      <% @service_rates.each do |service_rate| %>
          <tr class="<%= cycle :odd, :even %>">
            <td><%= service_rate.sku %></td>
            <td><%= service_rate.description %></td>
            <td><%= number_to_currency(service_rate.rate) %></td>
            <td><%= service_rate.taxable %></td>
            <td><%= number_to_percentage(service_rate.tax_rate) %></td>
            <td><%= service_rate.active %></td>
            <td>
              <a class="btn btn-small" href="<%= service_rate_path(service_rate) %>"><i class="icon-eye-open"></i><%= t("global.view") %>
              </a>
              <a class="btn btn-small" href="<%= edit_service_rate_path(service_rate) %>"><i class="icon-edit"></i><%= t("global.edit") %>
              </a>
            </td>
          </tr>
      <% end %>

      </tbody>
    </table>
  </div>
  <div class="span2">
    <%= menu_button (t "global.create"), new_service_rate_path, "icon-plus icon-white" %>
  </div>
</div>


app/views/service_rates/new.html.erb
<div class="row-fluid">
  <div class="span10">
    <div class="tabbable"> <!-- Only required for left/right tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><a href="#basic" data-toggle="tab"><%= t("products.tab_menu_basic") %></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="basic">
          <p><%= render(:partial => 'form') %></p>
        </div>

      </div>
    </div>
  </div>

  <div class="span2">
    <%= menu_button (t "global.exit"), service_rates_path, "icon-pencil icon-white" %>
  </div>
</div>

app/views/service_rates/show.html.erb

<div id="sidebar_left">
  <%= module_header %>
  <div class="module">
    <ul>
      <% if can? :read, @products %><li class="delete"><%= link_to (t "global.delete"), @service_rate, :confirm => 'Are you sure?', :method => :delete %></li> <% end %>
      <% if can? :edit, @products %><li class="edit"><%= link_to (t "global.edit"), edit_service_rate_path(@service_rate) %></li> <% end %>
      <li class="exit"><%= link_to (t "global.exit"), service_rates_path %></li>
    </ul>
  </div>
<%= render 'layouts/left_sidebar_modules' %>
</div>
<div id="center_col" class="no_right_sidebar">
<div id="ddtabs1" class="basictab" >
<ul>
<li><a href="#<%= t "products.tab_menu_basic_name"  %>" rel="tab1"><%= (t "products.tab_menu_basic") %></a></li>
</ul>
</div>

<div class="tabcontainer">

<div id="tab1" class="tabcontent">
  <p>
    <b>Sku:</b>
    <%= @service_rate.sku %>
  </p>

  <p>
    <b>Description:</b>
    <%= @service_rate.description %>
  </p>

  <p>
    <b>Rate:</b>
    <%= number_to_currency(@service_rate.rate) %>
  </p>

  <p>
    <b>Taxable:</b>
    <%= @service_rate.taxable %>
  </p>

  <p>
    <b>Tax rate:</b>
    <%= @service_rate.tax_rate %>
  </p>

  <p>
    <b>Active:</b>
    <%= @service_rate.active %>
  </p>

  <fieldset id="collapsable">
    <table>
      <tr>
        <td  >
          <h1><%= t "global.transaction_log" %></h1>
        </td>
      </tr>
      <tr>
        <td  >
          <strong><%= t "supplier.date_created" %>:</strong>
        </td>
        <td align="left">
          <%= time_ago_in_words(@service_rate.created_at) %> <%= t "global.ago" %>
          (<%= localize @service_rate.created_at, :format => :short %>).
        </td>
      </tr>
      <tr>
        <td >
          <strong><%= t "global.last_updated_by" %>:</strong>
        </td>
        <td align="left">
              <%= time_ago_in_words(@service_rate.created_at) %> <%= t "global.ago" %>
              (<%= localize @service_rate.created_at, :format => :short %>).

        </td>
      </tr>
    </table>
  </fieldset>
</div>
</div>
</div>