config/routes.rb
MyITCRM2::Application.routes.draw do

  resources :roles
  resources :permissions
  resources :permittables

  resources :users do
    collection do
      put :edit_profile
      put :update_profile
      put :register
    end
      resources :invoices, :work_orders
  end

  resources :pages
  resources :page_categories do
    get :page_category_name, :on => :collection
  end


  resources :statuses
  resources :priority_lists


  resources :work_orders do
    collection do
      put :close
      put :assign
    end
    resources :replies, :invoices, :tasks
  end
  resources :invoices do
     resources :product_invoice_lines, :service_invoice_lines
    end

  resources :settings do
    collection do
      get :index
      put :edit
    end
  end

  resources :product_categories do
    get :product_category_name, :on => :collection
  end

  resources :user_sessions

  resources :suppliers
  resources :products
  resources :service_rates
  resources :replies, :only => [:show, :edit, :update]
  resources :tasks, :only => [:index, :show, :edit, :update]
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/register' => 'users#register', :as => :register
  match '/clients' => 'users#clients', :as => :clients
  match '/employees' => 'users#employees', :as => :employees
  match 'profile/:id' => 'users#edit_profile', :as => :my_account
  match 'work_orders/:id/close' => 'work_orders#close', :as => :close
  match 'work_order/:id/assign' => 'work_orders#assign', :as => :assign
  match 'settings/edit' => 'settings#edit', :as => :edit

  match 'help/:page_id' => 'help#show'
  get '*page_category/:id' => 'pages#show', :only => [:show]



  root :to => 'user_sessions#new'











end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :priority_list
  belongs_to :status
  belongs_to :user
  has_many :replies, :dependent => :destroy  # Destroy's the associated replies if a Work Order is deleted
  has_many :tasks, :dependent => :destroy  # Destroy's the associated tasks if a Work Order is deleted

# Validate presence of Input information when creating or editing
  validates_presence_of :subject, :description

  attr_accessible :description, :subject, :priority_list_id, :edited_by, :created_by, :user_id, :task_id

  before_update :workorder_updated, :change_assignment, :lookup_assigned_username, :change_status



     def workorder_updated
      if self.closed?
        self.status_id = 4
        self.closed_by = edited_by
      end
      # When updating occurs, lets check to see if the status
      # has changed to new and if so lets remove the assigned user details
      if self.status_id == 1
        self.assigned_to_id ||= nil
        self.assigned_to_username ||= nil
      end
    end

  def change_assignment
      #  This will change the status from NEW to Assigned when a user is assigned to a NEW Work Order
      if self.assigned_to_username.blank?
        #     If there is no assigned user, it will change the status back to NEW
        new_wo_status = "1"
        self.status_id = new_wo_status
      else
        if self.status_id == 1
          new_wo_status = "2"
          self.status_id = new_wo_status
        end
      end
    end
      # On Update if the closed value is true then we assign it the closed status and
      # add the time as to when it was closed.
      def change_status
        if self.closed?
          self.status_id = 6
          self.closed_date = Time.now
        end
      end

  private
# Used to obtain the Assigned Users name from the database on Work Order saving,
# instead of making a separate call each time it's displayed in the table
  def lookup_assigned_username
    if self.assigned_to_username.blank?
        self.assigned_to_id = nil
      else
        assigned_user = User.where(["name = ?", assigned_to_username]).first
        self.assigned_to_id = assigned_user.id
      end
  end
end


app/controllers/work_orders_controller.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class WorkOrdersController < ApplicationController
  before_filter :login_required # User must be logged in first
  authorize_resource # Used by CanCan to restrict controller access
  helper_method :sort_column, :sort_direction # Used for sorting columns

  def index
    @title = t "workorder.t_workorders"
    if current_user.client
      @new_work_orders = WorkOrder.where("status_id = 1 AND user_id = ?", current_user.id)
      @assigned_work_orders = WorkOrder.where("status_id = 2 AND user_id = ?", current_user.id)
      @on_hold_work_orders = WorkOrder.where("status_id = 3 AND user_id = ?", current_user.id)
      @pending_work_orders = WorkOrder.where("status_id = 4 AND user_id = ?", current_user.id)
      @re_opened_work_orders = WorkOrder.where("status_id = 5 AND user_id = ?", current_user.id)
      @closed_work_orders = WorkOrder.where("status_id = 6 AND user_id = ?", current_user.id).order("closed_date DESC")
    elsif can? :manage, WorkOrder
      @new_work_orders = WorkOrder.where("status_id = 1")
      @assigned_work_orders = WorkOrder.where("status_id = 2")
      @on_hold_work_orders = WorkOrder.where("status_id = 3")
      @pending_work_orders = WorkOrder.where("status_id = 4")
      @re_opened_work_orders = WorkOrder.where("status_id = 5")
      @closed_work_orders = WorkOrder.where("status_id = 6").order("closed_date DESC")
    end
  end

  def show

    @work_order = WorkOrder.find(params[:id])
    @invoiced = Invoice.find_all_by_work_order_id(params[:id]).first
    @reply = Reply.new(:work_order_id => @work_order.id)
    @task = Task.new(:work_order_id => @work_order.id, :user_id => current_user.id)
    @tasks = Task.find_all_by_work_order_id(params[:id])
    @title = (t "workorder.t_viewing_workorder_details") + ' #' + params[:id].to_s + ' ' + t('global.for') + ' ' + @work_order.user.name
  end

  def new
    @work_order = WorkOrder.new
    if can? :create, WorkOrder
      if params[:user_id].present? and current_user.client
        @client = User.find(current_user.id)
        @title = (t "workorder.creating_wo_for")+@client.name.camelcase
      else
        if params[:user_id].present? and current_user.employee
          @client = User.find(params[:user_id])
          @title = (t "workorder.creating_wo_for")+@client.name.camelcase
        end
      end
      if params[:user_id].blank? and current_user.employee
        redirect_to clients_url
        flash[:info] = t('message.info.select_client_first')
      end

    end

  end

  def edit
    @title = (t "workorder.t_edit") + ' #' + params[:id].to_s
    @work_order = WorkOrder.find(params[:id])
    @task = Task.new(:work_order_id => @work_order.id, :user_id => current_user.id)
  end

  def create
    @title = t "workorder.t_workorders"
    @work_order = WorkOrder.new
    if can? :create, WorkOrder
      @work_order.user_id = params[:user_id] if current_user.employee?
      @work_order.user_id = current_user.id if current_user.client?
      @work_order.created_at = Time.now
      @work_order.status_id = 1 # Applies a status of "NEW" by default
      @work_order.closed = 0 # Work Order is not "closed" by default
      @work_order.created_by = current_user.username
    end
    @work_order.attributes = params[:work_order]
    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, notice: 'Work Order was successfully created.' }
      else
        redirect_to(:back)
      end
    end
  end

  def update
    @title = (t "workorder.t_workorders") + ' #' + params[:id].to_s
    @work_order = WorkOrder.find(params[:id])
    @work_order.user_id = current_user.id if current_user.client
    @work_order.edited_by = current_user.username
    @work_order.dynamic_attributes = [:status_id, :resolution, :assigned_to_username, :closed] if can? :manage, WorkOrder
    invoicing_enabled = true

    if invoicing_enabled.present? and @work_order.closed
      respond_to do |format|
        if @work_order.update_attributes(params[:work_order])
          flash[:notice] = 'Work Order was successfully updated.'
          format.html { redirect_to new_work_order_invoice_path(:work_order_id => @work_order.id) }
          format.xml { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml { render :xml => @work_order.errors, :status => :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @work_order.update_attributes(params[:work_order])
          flash[:notice] = 'Work Order was successfully updated.'
          format.html { redirect_to(@work_order) }
          format.xml { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml { render :xml => @work_order.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  def close
    @title = (t "workorder.t_workorders") + ' #' + params[:id].to_s
    @work_order = WorkOrder.find(params[:id])
    #@work_order.edited_by = current_user.username
    #@work_order.closed_by = current_user.username
    #@work_order.dynamic_attributes = [:status_id, :resolution, :assigned_to_username, :closed] if can? :manage, WorkOrder
    #invoicing_enabled = true
    if @work_order.assigned_to_id.blank?
      redirect_to(@work_order)
      flash[:alert] = "Work Order needs to be assigned to an employee first before closing."
      respond_to do |format|
        if @work_order.update_attributes(params[:work_order])
          flash[:notice] = 'Work Order was successfully closed.'
          format.html { redirect_to(@work_order) }
          format.xml { head :ok }
        else
          format.html { render :action => "close" }
          format.xml { render :xml => @work_order.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  def assign
    @title = (t "workorder.t_workorders") + ' #' + params[:id].to_s
    @work_order = WorkOrder.find(params[:id])
# Only change status if the status is either NEW or Assigned
    @status = @work_order.status_id = 2 if @work_order.status_id < 3
    respond_to do |format|
      if @work_order.update_attributes(params[:work_order])
        flash[:notice] = t "workorder.message_assigned_success"
        format.html { redirect_to(work_orders_url) }
        format.xml { head :ok }
      else
        format.html { render :action => "assign" }
        format.xml { render :xml => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @title = (t "workorder.t_workorders") + ' #' + params[:id].to_s
    @work_order = WorkOrder.find(params[:id])
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to(work_orders_url) }
      format.xml { head :ok }
    end
  end


  private

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[ASC DESC].include?(params[:direction]) ? params[:direction] : "ASC"
  end
end

app/helpers/work_orders_helper.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module WorkOrdersHelper
  def invoice(work_order_id = nil)
    Invoice.where("work_order_id = ?", "#{work_order_id}")
  end

  def replies
    @replies = Reply.where("work_order_id = ?", "#{params[:id]}").order("id DESC").paginate(:per_page => 10, :page => params[:page])
  end

  def tasks
    @tasks = Task.where("work_order_id = ?", "#{params[:id]}").order("id DESC")
  end

  def reply
    @reply = Reply.new
  end

  def priority_badge(priority_list_id = nil, priority_list_name = nil)
    priority_list_id == priority_list_id.to_i
    if priority_list_id == 1 then
      "<span class='label'>#{priority_list_name}</span>".html_safe
    else
      if priority_list_id == 2 then
        "<span class='label label-info'>#{priority_list_name}</span>".html_safe
      else

        if priority_list_id == 3 then
          "<span class='label label-warning'>#{priority_list_name}</span>".html_safe
        else
          if priority_list_id == 4 then
            "<span class='label label-important'>#{priority_list_name}</span>".html_safe
          else
            if priority_list_id == 5 then
              "<span class='label label-inverse'>#{priority_list_name}</span>".html_safe
            end
          end
        end
      end
    end


  end

  #@invoiced = Invoice.find_all_by_work_order_id(params[:id]).first

  #@replies = Reply.where("work_order_id = ?","#{params[:id]}").order("id DESC").paginate(:per_page => 4, :page => params[:page])


end

app/views/work_orders/_assigned_wo_tab.html.erb
<table class="table table-bordered table-hover table table-condensed">
  <thead>
      <tr>
        <th><%= t "workorder.index.t_wo" %></th>
            <th><%= t "workorder.priority" %></th>
            <th><%= t "global.client" %></th>
            <th><%= t "global.subject" %></th>
            <th><%= t "workorder.assigned_to" %></th>
            <th><%= t "global.actions" %></th>
      </tr>
    </thead>
    <tbody>
    <% @assigned_work_orders.each do |assigned_wo| %>
      <tr>
        <td style="text-align: left!important;" ><a href="<%= work_order_path(assigned_wo.id) %>" rel="tooltip" data-placement="right" data-original-title="
                <%= t "global.created_at" %>:<%= l assigned_wo.created_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= assigned_wo.created_by %>
                <%= t "global.updated_at" %>:<%= l assigned_wo.updated_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= assigned_wo.edited_by %>"><%= assigned_wo.id %></a></td>
            <td><%= priority_badge assigned_wo.priority_list.id,  assigned_wo.priority_list.name %></td>
            <td><%= link_to(assigned_wo.user.name, user_path(assigned_wo.user_id)) %></td>
            <td><%= truncate(assigned_wo.subject, :length => 100) %></td>
            <td><%= assigned_wo.assigned_to_username %></td>
            <td>
              <% if can? :manage, WorkOrder %>
              <a class="btn btn-small" href="<%= work_order_url(assigned_wo.id) %>"><i class="icon-search"></i><%= t("global.view") %></a>
              <a class="btn btn-small" href="<%= edit_work_order_url(assigned_wo.id) %>"><i class="icon-pencil"></i><%= t("global.edit") %></a>
              <a class="btn btn-small" href="<%= work_order_path(assigned_wo.id,:format => 'pdf') %>"><i class="icon-print"></i><%= t("global.print") %></a>
              <% end %>
            </td>
      </tr>
    <% end %>
    </tbody>
</table>


app/views/work_orders/_close.html.erb
<%= simple_form_for @work_order, :class => "form-horizontal" do |f| %>
    <%= f.input :closed, :input_html => {:checked => true} %>
    <%= markdown_hint %>
    <%= f.input :resolution, :input_html => {:rows => 7, :cols => 40} %>
    <div class="form-actions">
      <%= f.submit nil, :class => "btn btn-primary" %>
      <%= link_to t("global.cancel"), work_order_path, :class => "btn" %>
    </div>
<% end %>

app/views/work_orders/_new_wo_tab.html.erb
<table class="table table-bordered table-hover table table-condensed">
  <thead>
      <tr>
        <th style="text-align: left!important;"><%= t "workorder.index.t_wo" %></th>
            <th><%= t "workorder.priority" %></th>
            <th><%= t "global.client" %></th>
            <th><%= t "global.subject" %></th>
            <th><%= t "global.actions" %></th>
      </tr>
    </thead>
    <tbody>
    <% @new_work_orders.each do |new_wo| %>
      <tr>
        <td><a href="<%= work_order_path(new_wo.id) %>" rel="tooltip" data-placement="right" data-original-title="
                [<%= t "global.created_at" %>:<%= l new_wo.created_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= new_wo.created_by %>]&nbsp;&nbsp;&nbsp;
                [<%= t "global.updated_at" %>:<%= l new_wo.updated_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= new_wo.edited_by %>]"><%= new_wo.id %></a></td>
            <td><%= priority_badge new_wo.priority_list.id,  new_wo.priority_list.name %></td>
            <td><%= link_to(new_wo.user.name, user_path(new_wo.user.id) )%></td>
            <td><%= truncate(new_wo.subject, :length => 100 ) %></td>
            <td>
              <% if can? :manage, WorkOrder %>
              <a class="btn btn-small" href="<%= work_order_url(new_wo.id) %>"><i class="icon-eye-open"></i><%= t("global.view") %></a>
              <a class="btn btn-small" href="<%= edit_work_order_url(new_wo.id) %>"><i class="icon-pencil"></i><%= t("global.edit") %></a>
              <a class="btn btn-small" href="<%= work_order_path(new_wo.id,:format => 'pdf') %>"><i class="icon-print"></i><%= t("global.print") %></a>
              <% end %>
            </td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/work_orders/_on_hold_wo_tab.html.erb
<table class="table table-bordered table-hover table table-condensed">
  <thead>
      <tr>
        <th><%= t "workorder.index.t_wo" %></th>
            <th><%= t "workorder.priority" %></th>
            <th><%= t "global.client" %></th>
            <th><%= t "global.subject" %></th>
            <th><%= t "workorder.assigned_to" %></th>
            <th><%= t "global.actions" %></th>
      </tr>
    </thead>
    <tbody>
    <% @on_hold_work_orders.each do |on_hold| %>
      <tr>
        <td><a href="<%= work_order_path(on_hold.id) %>" rel="tooltip" data-placement="right" data-original-title="
                <%= t "global.created_at" %>:<%= l on_hold.created_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= on_hold.created_by %>
                <%= t "global.updated_at" %>:<%= l on_hold.updated_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= on_hold.edited_by %>"><%= on_hold.id %></a></td>
            <td><%= priority_badge on_hold.priority_list.id,  on_hold.priority_list.name %></td>
            <td><%= link_to(on_hold.user.name, user_path(on_hold.user_id)) %></td>
            <td><%= truncate(on_hold.subject, :length => 100) %></td>
            <td><%= on_hold.assigned_to_username %></td>
            <td>
              <% if can? :manage, WorkOrder %>
              <a class="btn btn-small" href="<%= work_order_url(on_hold.id) %>"><i class="icon-search"></i><%= t("global.view") %></a>
              <a class="btn btn-small" href="<%= edit_work_order_url(on_hold.id) %>"><i class="icon-pencil"></i><%= t("global.edit") %></a>
              <a class="btn btn-small" href="<%= work_order_path(on_hold.id,:format => 'pdf') %>"><i class="icon-print"></i><%= t("global.print") %></a>
              <% end %>
            </td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/work_orders/_pending_wo_tab.html.erb
<table class="table table-bordered table-hover table table-condensed">
  <thead>
      <tr>
        <th><%= t "workorder.index.t_wo" %></th>
            <th><%= t "workorder.priority" %></th>
            <th><%= t "global.client" %></th>
            <th><%= t "global.subject" %></th>
            <th><%= t "workorder.assigned_to" %></th>
            <th><%= t "global.actions" %></th>
      </tr>
    </thead>
    <tbody>
    <% @pending_work_orders.each do |pending| %>
      <tr>
        <td><a href="<%= work_order_path(pending.id) %>" rel="tooltip" data-placement="right" data-original-title="
                <%= t "global.created_at" %>:<%= l pending.created_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= pending.created_by %>
                <%= t "global.updated_at" %>:<%= l pending.updated_at, :format => :medium %>&nbsp;<%= t "global.by" %>&nbsp;<%= pending.edited_by %>"><%= pending.id %></a></td>
            <td><%= priority_badge pending.priority_list.id,  pending.priority_list.name %></td>
            <td><%= link_to(pending.user.name, user_path(pending.user_id)) %></td>
            <td><%= truncate(pending.subject, :length => 100) %></td>
            <td><%= pending.assigned_to_username %></td>
            <td>
              <% if can? :manage, WorkOrder %>
              <a class="btn btn-small" href="<%= work_order_url(pending.id) %>"><i class="icon-search"></i><%= t("global.view") %></a>
              <a class="btn btn-small" href="<%= edit_work_order_url(pending.id) %>"><i class="icon-pencil"></i><%= t("global.edit") %></a>
              <a class="btn btn-small" href="<%= work_order_path(pending.id,:format => 'pdf') %>"><i class="icon-print"></i><%= t("global.print") %></a>
              <% end %>
            </td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/work_orders/_tasks_table.html.erb
<div class="span10 offset2">
  <h3>Tasks</h3>
  <table class="table table-bordered table-condensed">
              <tr>
              <th>Task Title</th>
              <th>Task Description</th>
              <th>Task Due Date</th>
              <th>Task Completed</th>
              </tr>
          <% tasks.each do |task| %>
              <tr>
                <td><%= link_to task.title, task_path(task.id) %></td>
                <td><%= task.description %></td>
                <td><%= task.calendar_id %></td>
                <td><%= task.completed %></td>
              </tr>
          <% end %>
          </table>
</div>


app/views/work_orders/show.html.erb
<div class="span10">
  <div class="form-horizontal">
    <div class="control-group">
      <label class="control-label"><%= t "workorder.subject" %>:</label>

      <div class="controls">
        <span class="span6 uneditable-input"><%= @work_order.subject %></span>
      </div>
    </div>
    <% if @work_order.closed? %>
        <label class="control-label"><%= t "workorder.assigned_to" %></label>

        <div class="controls">
          <span class="input uneditable-input"><%= @work_order.assigned_to_username %></span>
        </div><br>
    <% else %>
        <label class="control-label"><%= t "workorder.assigned_to" %></label>

        <div class="controls">
          <% if current_user.workorder_assignability? %>
              <%= render :partial => "assign" %>
          <% else %>
                  <span class="input-xlarge uneditable-input">
                    <% if @work_order.assigned_to_username.empty? %>
                        <%= t("workorder.not_assigned_message") %>
                    <% else %>
                     <%= @work_order.assigned_to_username %>
                    <% end %>
                    </span></div>
          <% end %>
          </div>
    <% end %>
    <div class="control-group">
      <label class="control-label"><%= t "workorder.priority" %>/<%= t "workorder.status" %>:</label>

      <div class="controls">
        <%= priority_badge @work_order.priority_list.id, @work_order.priority_list.name %> <%= t("global.and") %> <%= @work_order.status.name %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><%= t "workorder.details" %>:</label>

      <div class="controls" style="border: 2px #f5f5f5 solid;padding: 3px;">
        <%= markdown(@work_order.description) %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Messages</label>

      <div class="controls">
        <div><p><a href="#messages" role="button" class="btn" data-toggle="modal"><i class="icon-comment"></i> Add
          Message</a><%= will_paginate replies %></p></div>

        <!-- Modal -->
        <div id="messages" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Message</h3>
          </div>
          <div class="modal-body">
            <%= render :partial => 'replies/form' %>
          </div>
        </div>
        <ul class="media-list">
          <hr/>
          <% replies.each do |reply| %>
              <li class="media">
                <div class="pull-right muted">
                  <small>#<%= reply.id %></small>
                </div>
                <a class="pull-left" href="#">
                  <%= image_tag "blank_avatar.png", :size => "32x32" %>
                </a>

                <div class="media-body">
                  <h6 class="media-heading"><%= reply.user.name %> <%= t("global.wrote") %>:</h6>

                  <div class="media text-info">
                    <%= markdown(reply.content) %>
                    <span class="muted" style="font-size: 10px;">
                          <small>
                            <% if reply.updated_at > reply.created_at %> <i class="icon-edit"></i>
                                ( <%= t("global.edited") %> <%= l reply.updated_at, :format => :medium %> )
                            <% end %>
                            <%= time_ago_in_words(reply.created_at) %> <%= t("global.ago") %>
                            (<%= l reply.created_at, :format => :medium %>
                            )
                          </small>
                                               </span>
                    <% if @work_order.closed.blank? && if can? :edit, Reply %>
                        <%= link_to t("global.edit"), edit_work_order_reply_url(@work_order.id, reply.id), :class => "btn btn-info btn-mini" if can? :edit, Reply %>
                        <%= link_to t("global.delete"), work_order_reply_url(@work_order.id, reply.id), :confirm => t('alert.destroy'), :method => :delete, :class => "btn btn-danger btn-mini" if can? :manage, Reply %>
                    <% end %>
                    <% end %>
                  </div>
                </div>
              </li>
              <hr>
          <% end %>
        </ul>

      </div>
    </div>
    </div>
<div class="span10 small">
  <fieldset style="text-align:center;">
    <legend><%= t "global.activity_log" %></legend>
    <small>
      <strong><%= t "global.created_at" %>
        :</strong><%= time_ago_in_words(@work_order.created_at) %> <%= t "global.ago" %>
      (<%= l @work_order.created_at, :format => :short %>) <%= t "global.by" %> <%= @work_order.created_by %>.

      <% if @work_order.updated_at == nil %>
      <% else %>
          | <strong><%= t "global.updated_at" %>
      :</strong><%= time_ago_in_words(@work_order.updated_at) %> <%= t "global.ago" %>
          (<%= l @work_order.updated_at, :format => :short %>
          ) <%= t "global.by" %> <%= @work_order.edited_by %>.
      <% end %>
    </small>
  </fieldset>
</div>
</div>

<div class="span2">
  <% if @work_order.closed.blank? and can? :edit, WorkOrder %>
      <%= menu_button t("global.edit"), edit_work_order_path, "icon-pencil icon-white" %>
  <% end %>
  <% if can? :destroy, WorkOrder %>
      <%= menu_button t("global.print"), work_order_path(@work_order.id, :format => 'pdf'), "icon-print icon-white" %>
      <% if @work_order.closed %>
          <%= menu_button t("global.edit"), edit_work_order_path, "icon-pencil icon-white" if can? :manage, WorkOrder %>
          <% if @invoiced %>
              <%= menu_button t("invoice.show"), invoice_path(@invoiced.id), "icon-list-alt icon-white" %>
          <% else %>
              <%= menu_button t("invoice.create"), new_work_order_invoice_path(:work_order_id => @work_order.id, :user_id => @work_order.user_id), "icon-list-alt icon-white" %>
          <% end %>
      <% else %>
      <% end %>
  <% end %>
  <%= menu_button t("global.exit"), work_orders_path, "icon-arrow-left icon-white" %>
</div>