config/routes.rb
MyITCRM2::Application.routes.draw do

  resources :roles
  resources :permissions
  resources :permittables

  resources :users do
    collection do
      put :edit_profile
      put :update_profile
      put :register
    end
      resources :invoices, :work_orders
  end

  resources :pages
  resources :page_categories do
    get :page_category_name, :on => :collection
  end


  resources :statuses
  resources :priority_lists


  resources :work_orders do
    collection do
      put :close
      put :assign
    end
    resources :replies, :invoices, :tasks
  end
  resources :invoices do
     resources :product_invoice_lines, :service_invoice_lines
    end

  resources :settings do
    collection do
      get :index
      put :edit
    end
  end

  resources :product_categories do
    get :product_category_name, :on => :collection
  end

  resources :user_sessions

  resources :suppliers
  resources :products
  resources :service_rates
  resources :replies, :only => [:show, :edit, :update]
  resources :tasks, :only => [:index, :show, :edit, :update]
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/register' => 'users#register', :as => :register
  match '/clients' => 'users#clients', :as => :clients
  match '/employees' => 'users#employees', :as => :employees
  match 'profile/:id' => 'users#edit_profile', :as => :my_account
  match 'work_orders/:id/close' => 'work_orders#close', :as => :close
  match 'work_order/:id/assign' => 'work_orders#assign', :as => :assign
  match 'settings/edit' => 'settings#edit', :as => :edit

  match 'help/:page_id' => 'help#show'
  get '*page_category/:id' => 'pages#show', :only => [:show]



  root :to => 'user_sessions#new'











end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :product_category
  has_many :product_invoice_lines

  attr_accessible :our_sku, :description, :model, :manufacturer, :category_name, :supplier_id,
                  :supplier_sku, :cost_price, :sell_price, :created_by, :created_at, :product_category_id,
                  :product_category_name, :name, :updated_at, :warranty_info, :warranty_length, :warranty_unit

# Validations on inputs
  validates_presence_of :supplier, :description, :cost_price, :manufacturer, :model, :sell_price, :our_sku, :supplier_sku
  validates_uniqueness_of :our_sku
  validates_numericality_of :qty_allocated, :cost_price, :disc_amount, :disc_percent, :qty_available, :qty_on_hand, :qty_ordered, :sell_price, :tax_rate
  validates_numericality_of :disc_percent, :tax_rate, :less_than_or_equal_to => 100
  
# Define Active value to 1 on creation of new product
  before_create :create_product
  def create_product
    self.active ||= "1"
  end

# Search by 
  def self.search_products(search_products, sort_column, sort_direction)
      Product.where('description LIKE  ?', "%#{search_products}%").order(sort_column+ " "+sort_direction)

  end

  # Find or Create the ProductCategory for autocomplete
  def product_category_name
    product_category.try(:name)
  end

  def product_category_name=(name)
    self.product_category_id = ProductCategory.find_or_create_by_name(name) if name.present?
  end

  # Product Lookup Concatenated String for Invoicing
  def product_lookup
     # mytodo - Add currency symbol if possible.....
     "[#{our_sku}] - #{description} -#{I18n.t 'number.currency.format.unit'}#{sell_price}"
  end
end

app/controllers/products_controller.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class ProductsController < ApplicationController

  helper_method :sort_column, :sort_direction

#  Used by CanCan to restrict controller access
  authorize_resource

  def index
    @title = t "products.t_title"
#    @products = Product.paginate :page => params[:page], :order => sort_column+ " " +sort_direction, :per_page => 50
#    @products = Product.order(:id).page params[:page]
    @products = Product.search_products(params[:search_products], sort_column, sort_direction).paginate :per_page => 50, :page => params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @products }
    end
  end

  def show
    @title = t "products.t_title"
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @product }
    end
  end

  def new
    @title = t "products.t_add_new"
    @product = Product.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @product }
    end
  end

  def edit
    @title = t "products.t_title"
    @product = Product.find(params[:id])

  end

  def create
    @title = t "products.t_title"
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        flash[:notice] = 'Item was successfully created.'
        format.html { redirect_to(@product) }
        format.xml { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @title = t "products.t_title"
    @product = Product.find(params[:id])
    @product.dynamic_attributes = [:taxable, :tax_rate, :discountable, :disc_amount, :disc_percent] if can? :manage, Product

    respond_to do |format|
      if @product.update_attributes(params[:product])
        flash[:notice] = 'Item was successfully updated.'
        format.html { redirect_to(@product) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @title = t "products.t_title"
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml { head :ok }
    end
  end

  private

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "our_sku"
  end

  def sort_direction
    %w[ASC DESC].include?(params[:direction]) ? params[:direction] : "ASC"
  end
end
  

app/helpers/products_helper.rb
# MyITCRM - Repairs Business CRM Software
# Copyright (C) 2009-2014  Glen Vanderhel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


module ProductsHelper
end

app/views/products/_form.html.erb
<div id="ddtabs1" class="basictab" >
  <ul>
  <li><a href="#<%= t "products.tab_menu_basic_name"  %>" rel="sc1"><%= (t "products.tab_menu_basic") %></a></li>
  <li><a href="#<%= t "products.tab_menu_inventory_name" %>" rel="sc2"><%= t "products.tab_menu_inventory_name" %></a></li>
  <li><a href="#<%= t "products.tab_menu_selling_name" %>" rel="sc3"><%= t "products.tab_menu_selling" %></a></li>
  <li><a href="#<%= t "products.tab_menu_warranty_name"  %>" rel="sc4"><%= t "products.tab_menu_warranty" %></a></li>
  </ul>
  </div>

  <div class="tabcontainer">

  <div id="sc1" class="tabcontent">
  <%= simple_form_for @product do |f| %>
                  <%= f.input :our_sku, :label => (t "products.our_sku"), :hint => (t "products.hint.our_sku"), :input_html => {:size => 20} %>
                  <%= f.input :description, :label => (t "global.description"), :hint => (t "products.hint_desc") %>
                  <%= f.input :model, :label => (t "products.model"), :hint => (t "products.hint_model") %>
                  <%= f.input :manufacturer, :label => (t "products.manufacturer"), :hint => (t "products.hint_manuf") %>
                <div>
                    <%= f.label(t "products.category")%>
                    <p><%= f.text_field :product_category_name, data: {autocomplete_source: ProductCategory.order(:name).map(&:name)} %>
                  <span class="hint"><%= t "products.hint.category" %></span> </p>
                  </div>
              <% if params[:supplier_id].present? %>
              <div>
                  <%= f.label(t "products.supplier")%>
                      <p><%= f.text_field :supplier, :value => params[:supplier_name], :disabled => true  %></p>
                  <%= f.input :supplier_id, :as => :hidden, :input_html => {:value =>  params[:supplier_id]}   %>
              </div>
            <% else %>
             <% if @product.supplier_id.nil? %>
                <div>
                 <%= f.association :supplier, :label_method => :company_name, :label => (t "products.supplier") %> <%= f.label(t "supplier.t_add_new_supplier") %><%= link_to(image_tag('add.png', :title => (t "global.new")), new_supplier_path) %>
               </div>
              <% end %>
              <% end %>
                  <%= f.input :supplier_sku, :label =>(t "products.supplier_sku"),:hint => (t "products.hint.our_sku"), :input_html => {:size => 20} %>
                  <%= f.input :cost_price, :label =>(t "products.cost_price"), :input_html => {:size => 10} %>
                  <%= f.input :sell_price, :label =>(t "products.sell_price"), :input_html => {:size => 10} %>
                  <%= f.input :created_by, :as => :hidden, :input_html => {:value =>  current_user.username} %>
                  <%= f.input :created_at, :as => :hidden, :input_html => {:value =>  Time.now} %>

         <div class='center'>
          <%= f.button :submit%>
        </div>

          <% end %>
  </div>

  <div id="sc2" class="tabcontent">
  <%= simple_form_for @product do |f| %>
                  <%= f.input :stocked_product,:label =>(t "products.stocked")%>
                  <%= f.input :stocking_qty, :label =>(t "products.stocking_qty"), :hint => (t "products.hint.stocking_qty"),:input_html => {:size => 20} %>
                  <%= f.input :qty_on_hand, :label =>(t "products.qoh"), :input_html => {:size => 20} %>
                  <%= f.input :qty_allocated, :label =>(t "products.allocated"), :input_html => {:size => 20} %>
                  <%= f.input :qty_available, :label =>(t "products.available"), :input_html => {:size => 20} %>
                  <%= f.input :qty_ordered, :label =>(t "products.ordered"), :input_html => {:size => 20} %>

             <div class='center'>
          <%= f.button :submit%>
        </div>
          <% end %>
  </div>

  <div id="sc3" class="tabcontent">
  <%= simple_form_for @product do |f| %>
                  <%= f.input :taxable, :label =>(t "product.taxable") %>
                  <%= f.input :tax_rate, :label =>(t "products.tax_rate"), :hint => (t "products.hint_tax_rate"),  :input_html => {:value => Setting::tax_rate} %>
                  <%= f.input :discountable, :label =>(t "products.discountable") %>
                  <%= f.input :disc_amount, :label =>(t "products.disc_amount"), :input_html => {:size => 5} %>
                  <%= f.input :disc_percent,:label =>(t "products.disc_percent"), :input_html => {:size => 5} %>

        <div class='center'>
          <%= f.button :submit%>
        </div>
          <% end %>
  </div>
  <div id="sc4" class="tabcontent">
  <%= simple_form_for @product do |f| %>
                  <%= f.input :warranty_info, :as => :text, :input_html => {:rows => 15},:label =>(t "products.warranty_info") %>
                  <%= f.input :warranty_length, :input_html => {:size => 20}, :label =>(t "products.warranty_length") %>
                  <%= f.input :warranty_unit, :as => :select, :collection => [(t "global.days"), (t "global.months"), (t "global.years")],:label =>(t "products.warranty_units") %>

       <div class='center'>
          <%= f.button :submit%>
        </div>
          <% end %>
  </div>

  </div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div id="center_col" class="no_right_sidebar">
  <% form_tag products_path, :method => 'get' do %>
   <p><%= t "products.search"  %>
     <%=  text_field_tag :search_products, params[:search_products]  %>
     <%= submit_tag (t "global.submit"), :name => nil %>

   </p>
<% end %>
  <%= will_paginate @products %>



<table id="index_table" >
  <tr>
    <th><%= sortable "our_sku", (t "supplier.our_sku") %></th>
    <th><%= sortable "supplier_id", (t "supplier.supplier") %></th>
    <th><%= sortable "supplier_sku", (t "supplier.supplier_sku") %></th>
    <th><%= t "products.manufacturer" %></th>
    <th><%= t "global.description" %></th>
    <th><%= t "products.model" %></th>
    <th><%= sortable "cost_price", (t "products.cost") %></th>
    <th><%= sortable "sell_price", (t "products.sell_price") %></th>
    <th><%= sortable "qty_available", (t "products.available") %></th>
    <th><%= sortable "qty_ordered",  (t "products.ordered") %></th>
    <th><%= t "supplier.leadtime" %></th>
    <th><%= t "global.actions" %></th>
  </tr>

<% @products.each do |product| %>
  <tr align="left" class="<%= cycle :odd, :even %>">
    <td><%= link_to(product.our_sku, product) %></td>
    <td><%= link_to(product.supplier.company_name, supplier_path(product.supplier)) %></td>
    <td><%=h product.supplier_sku %></td>
    <td><%=h product.manufacturer %></td>
    <td><%=h product.description %></td>
    <td><%=h product.model %></td>
    <td><%=h number_to_currency(product.cost_price) %></td>
    <td><%=h number_to_currency(product.sell_price) %></td>
    <td><%=h product.qty_available %></td>
    <td><%=link_to(product.qty_ordered, products_path) %></td>
    <td><%=h product.supplier.parts_leadtime_days %></td>
    <td width="60"><%= link_to(image_tag('view.png', :title => (t "global.view")), product )%>
        <%= link_to(image_tag('edit.png', :title => (t "global.edit")), edit_product_path(product)) %>
        <%= link_to(image_tag('delete.png', :title => (t "global.delete")), product, :confirm => 'Are you sure?', :method => :delete ) %>
    </td>
  </tr>
<% end %>
</table>
</div>

app/views/products/new.html.erb
<%= render 'form' %>


app/views/products/show.html.erb
<!--mytodo -add all fields, -add tabs-->
<div id="sidebar_left">
  <%= module_header %>
  <div class="module">
    <ul>
      <% if can? :read, Product %><li class="delete"><%= link_to (t "global.delete"), @product, :confirm => 'Are you sure?', :method => :delete %></li> <% end %>
      <% if can? :edit, Product %><li class="edit"><%= link_to (t "global.edit"), edit_product_path %></li> <% end %>
      <li class="exit"><%= link_to (t "global.exit"), products_path %></li>
    </ul>
  </div>
<%= render 'layouts/left_sidebar_modules' %>
</div>
<div id="center_col" class="no_right_sidebar">
<div id="ddtabs1" class="basictab" >
<ul>
<li><a href="#<%= t "products.tab_menu_basic_name"  %>" rel="tab1"><%= (t "products.tab_menu_basic") %></a></li>
<li><a href="#<%= t "products.tab_menu_inventory_name" %>" rel="tab2"><%= t "products.tab_menu_inventory_name" %></a></li>
<li><a href="#<%= t "products.tab_menu_selling_name" %>" rel="tab3"><%= t "products.tab_menu_selling" %></a></li>
<li><a href="#<%= t "products.tab_menu_warranty_name"  %>" rel="tab4"><%= t "products.tab_menu_warranty" %></a></li>
</ul>
</div>

<div class="tabcontainer">

<div id="tab1" class="tabcontent">
  <table width="60%">
    <tr>
      <td >
        <strong><%= t "products.supplier" %>:</strong>
      </td>
      <td align="left">
        <%= @product.supplier.company_name %>
      </td>
    </tr>
    <tr>
      <td  >
        <strong><%= t "global.active" %></strong>
      </td>
      <td align="left">
        <%= @product.active? %>
      </td>
    </tr>
    <tr>
      <td >
        <strong><%= t "global.description" %>:</strong>
      </td>
      <td align="left">
        <%=  @product.description %>
      </td>
    </tr>
    <tr>
      <td >
        <strong><%= t "products.model" %>:</strong>
      </td>
      <td align="left">
        <%=  @product.model %>
      </td>
    </tr>
    <tr>
      <td  >
        <strong><%= t "products.cost" %>:</strong>
      </td>
      <td align="left">
        <%=  number_to_currency(@product.cost_price) %>
      </td>
    </tr>
    <tr>
      <td  >
        <strong><%= t "products.sell" %>:</strong>
      </td>
      <td align="left">
        <%=  number_to_currency(@product.sell_price) %>
      </td>
    </tr>
    <tr>
      <td  >
        <strong><%= t "products.sell" %>:</strong>
      </td>
      <td align="left">
        <%=  number_to_currency(@product.sell_price) %>
      </td>
    </tr>
    <tr>
  </table>
  <fieldset id="collapsable">
    <table>
      <tr>
        <td  >
          <h1><%= t "products.t_log" %></h1>
        </td>
      </tr>
      <tr>
        <td  >
          <strong><%= t "supplier.date_created" %>:</strong>
        </td>
        <td align="left">
          <%= time_ago_in_words(@product.created_at) %> <%= t "global.ago" %>
          (<%= localize @product.created_at, :format => :short %>) <%= t "global.by" %> <%= @product.created_by %>.
        </td>
      </tr>
      <tr>
        <td >
          <strong><%= t "global.last_updated_by" %>:</strong>
        </td>
        <td align="left">
          <% if @product.edited_at == nil %>
              <%= time_ago_in_words(@product.created_at) %> <%= t "global.ago" %>
              (<%= localize @product.created_at, :format => :short %>) <%= t "global.by" %> <%= @product.created_by %>.
          <% else %>
              <%= time_ago_in_words(@product.edited_at) %> <%= t "global.ago" %>
              (<%= localize @product.edited_at, :format => :short %>) <%= t "global.by" %> <%= @product.edited_by %>.
          <% end %>
        </td>
      </tr>
    </table>
  </fieldset>
</div>
<div id="tab2" class="tabcontent">

</div>
<div id="tab3" class="tabcontent">

</div>
<div id="tab4" class="tabcontent">

</div>
</div>
</div>